#!/bin/bash
if [ $# -ne 2 ]; then
    echo "Usage: $0 key value"
    exit 1
fi
d=$1
res="${d}=$2"
sed -i -e "s/${d}=.*\"/${res}\"/" /opt/freeswitch/conf/vars.xml
#"sound_prefix=\$\$\{sounds_dir\}/en/us/callie
